/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/brands/': {
		get: {
			responses: {
				/** @description Default Response */
				200: {
					content: {
						'application/json': {
							id: number;
							name: string;
							models: {
								id: number;
								name: string;
								brandId: number;
							}[];
						}[];
					};
				};
			};
		};
	};
	'/brands/{brandId}/models': {
		get: {
			parameters: {
				path: {
					brandId: number;
				};
			};
			responses: {
				/** @description Default Response */
				200: {
					content: {
						'application/json': {
							id: number;
							name: string;
							brandId: number;
						}[];
					};
				};
			};
		};
	};
	'/cars/count': {
		get: {
			responses: {
				/** @description Default Response */
				200: {
					content: {
						'application/json': number;
					};
				};
			};
		};
	};
	'/cars/latest': {
		get: {
			responses: {
				/** @description Default Response */
				200: {
					content: {
						'application/json': {
							id: number;
							images: string[];
							price: number;
							productionYear: number;
							miles: number;
							fuel: string;
							engine: number;
							body: string;
							transmission: string;
							brandId: number;
							brand: {
								id: number;
								name: string;
							};
							modelId: number;
							model: {
								id: number;
								name: string;
							};
						}[];
					};
				};
			};
		};
	};
}

export type webhooks = Record<string, never>;

export interface components {
	schemas: {};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}

export type external = Record<string, never>;

export type operations = Record<string, never>;
