/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/brands/": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": ({
                id: number;
                name: string;
              })[];
          };
        };
      };
    };
  };
  "/brands/{brandId}/models": {
    get: {
      parameters: {
        path: {
          brandId: number;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": ({
                id: number;
                name: string;
                brandId: number;
              })[];
          };
        };
      };
    };
  };
  "/carOffers/": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": ({
                id: number;
                description: string;
                images: (string)[];
                price: number;
                productionYear: number;
                miles: number;
                fuel: string;
                gears: number;
                topSpeed: number;
                hp: number;
                doors: number;
                engine: number;
                body: string;
                transmission: string;
                brandId: number;
                brand: {
                  id: number;
                  name: string;
                };
                modelId: number | null;
                model: {
                  id: number;
                  name: string;
                } | null;
              })[];
          };
        };
      };
    };
  };
  "/carOffers/{carOfferId}": {
    get: {
      parameters: {
        path: {
          carOfferId: number;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              id: number;
              description: string;
              images: (string)[];
              price: number;
              productionYear: number;
              miles: number;
              fuel: string;
              gears: number;
              topSpeed: number;
              hp: number;
              doors: number;
              engine: number;
              body: string;
              transmission: string;
              brandId: number;
              brand: {
                id: number;
                name: string;
              };
              modelId: number | null;
              model: {
                id: number;
                name: string;
              } | null;
            };
          };
        };
      };
    };
  };
  "/carOffers/count": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": number;
          };
        };
      };
    };
  };
  "/carOffers/latest": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": ({
                id: number;
                description: string;
                images: (string)[];
                price: number;
                productionYear: number;
                miles: number;
                fuel: string;
                gears: number;
                topSpeed: number;
                hp: number;
                doors: number;
                engine: number;
                body: string;
                transmission: string;
                brandId: number;
                brand: {
                  id: number;
                  name: string;
                };
                modelId: number | null;
                model: {
                  id: number;
                  name: string;
                } | null;
              })[];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export type operations = Record<string, never>;
